[workspace]
resolver = "2"
members = ["ironx"]

[workspace.dependencies]
thiserror = { version = "2.0" }
serde = { version = "1.0", features = [] }
anyhow = { version = "1.0" }
tokio = { version = "1.46", features = ["full"] }
